name: release-nightly

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  nightly-docker-rootful:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 构建Docker镜像
      run: |
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_PWD }}
        docker build --no-cache -t jiangjiali/gitea:${{ github.event.inputs.tag_name }} .
        docker push jiangjiali/gitea:${{ github.event.inputs.tag_name }}
        docker save -o gitea.${{ github.event.inputs.tag_name }}.tar jiangjiali/gitea:${{ github.event.inputs.tag_name }}

    - name: 上载文件
      uses: actions/upload-artifact@v4
      with:
        name: gitea
        path: |
          gitea.${{ github.event.inputs.tag_name }}.tar
